[package]
name = "nimbus-node"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
async-trait = { workspace = true }

nimbus-common = { workspace = true }
nimbus-conf = { workspace = true }
nimbus-rt = { workspace = true }
