[package]
name = "nimbus-conf"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_yml = { workspace = true }
thiserror = { workspace = true }

nimbus-common = { workspace = true }
